
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jonathan
 */
public class TelaPrincipal2 extends javax.swing.JFrame {
int quantidadeSelecionada;
float iPhone7, iPhone7Plus, iPhone8, iPhone8Plus, iPhoneXR, iPhoneXS, iPhoneXSMax; 
        
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();

        String dataHoje = dateFormat.format(date);

       
    /**
     * Creates new form TelaPrincipal2
     */
    public TelaPrincipal2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtAguardandoPagamento = new javax.swing.JTextField();
        txtPagamentoRecusado = new javax.swing.JTextField();
        comboBoxQuantidade = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtItemComprado = new javax.swing.JComboBox();
        txtDescricao = new javax.swing.JLabel();
        txtErroSelecione = new javax.swing.JLabel();
        txtDigiteNome = new javax.swing.JLabel();
        txtErroQuantidade = new javax.swing.JLabel();
        txtComprou = new javax.swing.JLabel();
        botaoCartao = new javax.swing.JRadioButton();
        botaoBoleto = new javax.swing.JRadioButton();
        botaoTransferencia = new javax.swing.JRadioButton();
        txtFormaPagamento = new javax.swing.JLabel();
        txtValor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Costumer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Order");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Order Detail");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Selecione a forma de pagamento");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Item");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Efetuar a compra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNome.setText("Nome");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCidade.setText("Cidade");
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        txtData.setEditable(false);
        txtData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtData.setToolTipText("");
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        txtAguardandoPagamento.setEditable(false);
        txtAguardandoPagamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAguardandoPagamento.setText("Aguardando pgmt");
        txtAguardandoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAguardandoPagamentoActionPerformed(evt);
            }
        });

        txtPagamentoRecusado.setEditable(false);
        txtPagamentoRecusado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPagamentoRecusado.setText("Pagamento recusado");
        txtPagamentoRecusado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagamentoRecusadoActionPerformed(evt);
            }
        });

        comboBoxQuantidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        comboBoxQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxQuantidadeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Quantidade:");

        txtItemComprado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um produto", "iPhone 7 128GB", "iPhone 7 Plus 64GB", "iPhone 8 256GB", "iPhone 8 Plus 256GB", "iPhone XR 128GB", "iPhone XS 256GB", "iPhone XS Max 512GB" }));
        txtItemComprado.setToolTipText("");
        txtItemComprado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCompradoActionPerformed(evt);
            }
        });

        txtErroSelecione.setForeground(new java.awt.Color(255, 0, 51));

        txtDigiteNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDigiteNome.setForeground(new java.awt.Color(255, 51, 51));
        txtDigiteNome.setToolTipText("");

        txtErroQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtErroQuantidade.setForeground(new java.awt.Color(255, 51, 0));

        txtComprou.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtComprou.setForeground(new java.awt.Color(0, 153, 102));

        buttonGroup1.add(botaoCartao);
        botaoCartao.setSelected(true);
        botaoCartao.setText("Cartão de crédito até 12x");

        buttonGroup1.add(botaoBoleto);
        botaoBoleto.setText("Boleto bancário 5% desconto");

        buttonGroup1.add(botaoTransferencia);
        botaoTransferencia.setText("Transferência Bancária");

        txtFormaPagamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFormaPagamento.setForeground(new java.awt.Color(255, 51, 51));

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtValor.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(127, 127, 127))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(197, 197, 197)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(txtData)
                                    .addComponent(txtAguardandoPagamento)))
                            .addComponent(txtDigiteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComprou))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFormaPagamento)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPagamentoRecusado, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboBoxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtErroQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtItemComprado, 0, 142, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtErroSelecione)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoCartao)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botaoBoleto)
                            .addComponent(botaoTransferencia))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(2, 2, 2)
                        .addComponent(txtErroSelecione)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPagamentoRecusado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtItemComprado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(29, 29, 29))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboBoxQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDigiteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtErroQuantidade))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtComprou)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFormaPagamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoCartao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoBoleto)
                        .addGap(15, 15, 15)
                        .addComponent(botaoTransferencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAguardandoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabel7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 153, 0));
        jLabel7.setText("Loja do iPhone - Compre aqui seu novo smartphone!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        String getNome = txtNome.getText(); 
        String getCidade = txtCidade.getText(); 
        
        
        if ("Nome".equals(getNome) || "".equals(getNome)) { 
            txtDigiteNome.setText("Você deve digitar o seu nome e a cidade");
        } else 
        
        if ("Cidade".equals(getCidade) || "".equals(getCidade)) { 
            txtDigiteNome.setText("Você deve digitar o seu nome e a cidade");
        }
        
        else
        if(txtItemComprado.getSelectedItem().equals("Selecione um produto")) {
            txtErroSelecione.setText("Selecione um produto abaixo!");
        }
        
        else
            if(comboBoxQuantidade.getSelectedItem().equals("0")) {
                txtErroQuantidade.setText("Selecione a quantidade");
            }
            
        else 
            if(botaoBoleto.isSelected()== true) {
                
     
            int i = JOptionPane.showConfirmDialog(null, "Deseja realmente comprar por boleto bancário?");
            if (i== JOptionPane.YES_OPTION) {
            
        txtAguardandoPagamento.setText("Pagamento OK");
        txtAguardandoPagamento.setBackground(Color.green);
        txtPagamentoRecusado.setText("Pagamento Aprovado"); 
        txtPagamentoRecusado.setBackground(Color.green);
        
        txtDigiteNome.setText("");
        txtErroSelecione.setText("");
        txtErroQuantidade.setText("");
        
        txtComprou.setText("<html>Parabens, "+txtNome.getText()+" você comprou "+comboBoxQuantidade.getSelectedItem()+"x "+txtItemComprado.getSelectedItem()+" !<br/><br/>O seu telefone sera enviado em ate 48h para "+txtCidade.getText()+"<br/><br/>Método de pagamento: Boleto Bancário</html>");
            } 
            
            else{
                repaint();
            }
        }
        
        else 
            if(botaoCartao.isSelected()== true) {
                
     
            int i = JOptionPane.showConfirmDialog(null, "Deseja realmente comprar por cartão em até 12x?");
            if (i== JOptionPane.YES_OPTION) {
            
        txtAguardandoPagamento.setText("Pagamento OK");
        txtAguardandoPagamento.setBackground(Color.green);
        txtPagamentoRecusado.setText("Pagamento Aprovado"); 
        txtPagamentoRecusado.setBackground(Color.green);
        
        txtDigiteNome.setText("");
        txtErroSelecione.setText("");
        txtErroQuantidade.setText("");
        
        txtComprou.setText("<html>Parabens, "+txtNome.getText()+" você comprou "+comboBoxQuantidade.getSelectedItem()+"x "+txtItemComprado.getSelectedItem()+" !<br/><br/>O seu telefone sera enviado em ate 48h para "+txtCidade.getText()+"<br/><br/>Método de pagamento: Cartão de crédito em até 12x</html>");
            } 
            
            else{
                repaint();
            }
        }
        
        else 
            if(botaoTransferencia.isSelected()== true) {
                
     
            int i = JOptionPane.showConfirmDialog(null, "Deseja realmente realizar transferencia?");
            if (i== JOptionPane.YES_OPTION) {
            
        txtAguardandoPagamento.setText("Pagamento OK");
        txtAguardandoPagamento.setBackground(Color.green);
        txtPagamentoRecusado.setText("Pagamento Aprovado"); 
        txtPagamentoRecusado.setBackground(Color.green);
        
        txtDigiteNome.setText("");
        txtErroSelecione.setText("");
        txtErroQuantidade.setText("");
        
        txtComprou.setText("<html>Parabens, "+txtNome.getText()+" você comprou "+comboBoxQuantidade.getSelectedItem()+"x "+txtItemComprado.getSelectedItem()+" !<br/><br/>O seu telefone sera enviado em ate 48h para "+txtCidade.getText()+"<br/><br/>Método de pagamento: Transferência</html>");
            } 
            
            else{
                repaint();
            }
        }
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtAguardandoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAguardandoPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAguardandoPagamentoActionPerformed

    private void txtPagamentoRecusadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagamentoRecusadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagamentoRecusadoActionPerformed

    private void comboBoxQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxQuantidadeActionPerformed
        
       /* iPhone7     = (float) 2450.00;
        iPhone7Plus = (float) 2800.00;
        iPhone8     = (float) 3800.00; 
        iPhone8Plus = (float) 3400.00;
        iPhoneXR    = (float) 4200.00;     
        iPhoneXS    = (float) 6500.00;
        iPhoneXSMax = (float) 8800.00;     
        float soma;
        
        quantidadeSelecionada = (int) comboBoxQuantidade.getSelectedItem();
        
        if(quantidadeSelecionada > 0 && txtItemComprado.getSelectedItem().toString() == "iPhone 7 128GB") {
          soma = iPhone7 * quantidadeSelecionada;
          txtValor.setText(String.valueOf(soma));
       }
        */
    }//GEN-LAST:event_comboBoxQuantidadeActionPerformed

    private void txtItemCompradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCompradoActionPerformed
        txtItemComprado.getSelectedIndex();
        String texto = txtItemComprado.getSelectedItem().toString();
        
        
        
                
        if (texto == "iPhone 7 128GB") {
            txtDescricao.setText("<html>Este iPhone conta com tela de 4.7' <br/> e armazenamento total de 128GB <br/>Peso: 510g<br/><br/>Preço: "+iPhone7+"</html>");
     
        }
        
        if (texto == "Selecione um produto") {
            txtErroSelecione.setText("Por favor selecione o produto abaixo");
       
        }
        
        if(texto == "iPhone 7 Plus 64GB") {
            txtDescricao.setText("<html>Este iPhone conta com uma tela de 5.5' <br/>e armazenamento total de 64GB<br/>Peso: 478g<br/><br/>Preço: "+iPhone7Plus+"</html>");
        
        
        }
        
        if(texto == "iPhone 8 256GB"){
            txtDescricao.setText("<html>Um perfeito modelo entusiasta <br/>tela de 4.7' e armazenamento de 256GB<br/>Peso: 511g<br/><br/>Preço: "+iPhone8+"</html>");
        
        }
        
        
        if(texto == "iPhone 8 Plus 256GB"){
            txtDescricao.setText("<html>Ótimo para qm curte tudo em Full HD, <br/>tela de 5.5 e armazenamento de 256GB<br/>Peso: 278g<br/><br/>Preço: "+iPhone8Plus+"</html>");
        
        }
        
            
        if(texto == "iPhone XR 128GB") {
            txtDescricao.setText("<html>Um modelo de entrada para <br/>a evolução do iPhone X, conta com <br/>reconhecimento facial e 128GB<br/>Peso: 878g<br/><br/>Preço: "+iPhoneXR+"</html>");
        
        }
        
        if(texto == "iPhone XS 256GB") {
            txtDescricao.setText("<html>Este é ideal para você que <br/>quer o máximo de desempenho <br/>e funcionalidades, aparelho com 256GB<br/>Peso: 980g<br/><br/>Preço: "+iPhoneXS+"</html>");
        
        }
        
        if(texto == "iPhone XS Max 512GB"){
            txtDescricao.setText("<html>Com uma tela de 5.8' e equipado com <br/>eSim Card e juntamente com o Face ID <br/>você jamais encontrará outra tecnologia <br/>tão perfeita quanto este celular de 512GB<br/>Peso: 478g<br/><br/>Preço: "+iPhoneXSMax+"</html>");
        
        }
        
    }//GEN-LAST:event_txtItemCompradoActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
      
       LocalDate dataAgora = LocalDate.now();
       txtData.setText(String.valueOf(dataAgora));
        

    }//GEN-LAST:event_txtDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botaoBoleto;
    private javax.swing.JRadioButton botaoCartao;
    private javax.swing.JRadioButton botaoTransferencia;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboBoxQuantidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAguardandoPagamento;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JLabel txtComprou;
    private javax.swing.JTextField txtData;
    private javax.swing.JLabel txtDescricao;
    private javax.swing.JLabel txtDigiteNome;
    private javax.swing.JLabel txtErroQuantidade;
    private javax.swing.JLabel txtErroSelecione;
    private javax.swing.JLabel txtFormaPagamento;
    private javax.swing.JComboBox txtItemComprado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPagamentoRecusado;
    private javax.swing.JLabel txtValor;
    // End of variables declaration//GEN-END:variables
}
